disabled_rules:
- blanket_disable_command
- closure_body_length
- discarded_notification_center_observer
- discouraged_optional_boolean
- discouraged_optional_collection
- duplicate_enum_cases
- empty_xctest_method
- explicit_acl
- explicit_enum_raw_value
- explicit_self
- explicit_type_interface
- extension_access_modifier
- file_header
- file_name
- file_types_order
- generic_type_name
- inclusive_language
- joined_default_parameter
- large_tuple
- let_var_whitespace
- missing_docs
- nesting
- nimble_operator
- no_extension_access_modifier
- no_fallthrough_only
- no_grouping_extension
- notification_center_detachment
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- object_literal
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_unit_test
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_string_enum_value
- required_deinit
- required_enum_case
- shorthand_operator
- single_test_class
- sorted_imports
- strict_fileprivate
- superfluous_disable_command
- switch_case_on_newline
- todo
- trailing_newline
- trailing_whitespace
- type_contents_order
- untyped_error_in_catch
- unused_setter_value
- vertical_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- xctfail_message
- unavailable_function
- array_init
- explicit_top_level_acl
- orphaned_doc_comment
- multiple_closures_with_trailing_closure

opt_in_rules:
- contains_over_filter_count
- contains_over_filter_is_empty
- empty_collection_literal
- empty_count
- first_where
- force_cast
- force_try
- force_unwrapping
- is_disjoint
- last_where
- nsobject_prefer_isequal
- reduce_boolean
- reduce_into
- sorted_first_last
- unowned_variable_capture
- attributes
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_end_indentation
- closure_parameter_position
- collection_alignment
- colon
- comma
- compiler_protocol_init
- conditional_returns_on_newline
- contains_over_first_not_nil
- control_statement
- convenience_type
- deployment_target
- discouraged_direct_init
- discouraged_object_literal
- duplicate_imports
- dynamic_inline
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- explicit_init
- fallthrough
- fatal_error_message
- file_length
- for_where
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- identical_operands
- identifier_name
- implicit_getter
- implicit_return
- implicitly_unwrapped_optional
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- line_length
- literal_expression_end_indentation
- mark
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- private_action
- private_outlet
- private_over_fileprivate
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_type_annotation
- redundant_void_return
- return_arrow_whitespace
- statement_position
- static_operator
- strong_iboutlet
- switch_case_alignment
- syntactic_sugar
- toggle_bool
- trailing_closure
- trailing_comma
- trailing_semicolon
- type_name
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- void_return
- weak_delegate
- yoda_condition
- cyclomatic_complexity
- multiline_function_chains
- type_body_length

analyzer_rules:
- unused_import
- unused_declaration

unused_declaration:
contains_over_filter_count: error
contains_over_filter_is_empty: error
empty_collection_literal: error
first_where: error
force_cast: error
force_try: error
force_unwrapping: error
is_disjoint: error
last_where: error
nsobject_prefer_isequal: error
reduce_boolean: error
reduce_into: error
sorted_first_last: error
unowned_variable_capture: error
block_based_kvo: warning
class_delegate_protocol: warning
closing_brace: warning
closure_end_indentation: warning
closure_parameter_position: warning
comma: warning
compiler_protocol_init: warning
contains_over_first_not_nil: warning
control_statement: warning
convenience_type: warning
duplicate_imports: warning
dynamic_inline: warning
empty_enum_arguments: warning
empty_parameters: warning
empty_parentheses_with_trailing_closure: warning
empty_string: warning
explicit_init: warning
fallthrough: warning
fatal_error_message: warning
function_default_parameter_at_end: warning
identical_operands: warning
implicit_getter: warning
leading_whitespace: warning
legacy_cggeometry_functions: warning
legacy_constant: warning
legacy_constructor: warning
legacy_hashing: warning
legacy_multiple: warning
legacy_nsgeometry_functions: warning
legacy_random: warning
literal_expression_end_indentation: warning
mark: warning
multiline_arguments_brackets: warning
multiline_literal_brackets: warning
multiline_parameters_brackets: warning
operator_whitespace: warning
private_action: warning
protocol_property_accessors_order: warning
redundant_discardable_let: warning
redundant_nil_coalescing: warning
redundant_objc_attribute: warning
redundant_optional_initialization: warning
redundant_set_access_control: warning
redundant_type_annotation: warning
redundant_void_return: warning
return_arrow_whitespace: warning
static_operator: warning
strong_iboutlet: warning
syntactic_sugar: warning
toggle_bool: warning
trailing_semicolon: warning
unneeded_break_in_switch: warning
unneeded_parentheses_in_closure_argument: warning
unused_closure_parameter: warning
unused_control_flow_label: warning
unused_enumerated: warning
valid_ibinspectable: warning
vertical_parameter_alignment: warning
vertical_parameter_alignment_on_call: warning
void_return: warning
weak_delegate: warning
yoda_condition: warning

attributes:
    attributes_with_arguments_always_on_line_above: false

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 65
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 60
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
    ignores_case_statements: true
reporter: "xcode"
